PlayerStorageDefaultCapacity: 1024 # 창고 PlayerStorage.Instance
PetCapcity: 8 # 8 초과시 초과분 안보임. PetProxy.Instance.Inventory
InventoryCapacity: 8 # 가방 배율
WeightMultiplier: 0 # 무게 배율
MaxStackCount: 2000000000 # 중첩 , IsBullet, Cash, Item_FlamingCore, Item_ColdCore, Item_Feather 깃털
MaxDurability: 2000000000 # 내구
MaxHealth: 2000000000 #  
CharacterRunSpeed: 8 #  
CharacterWalkSpeed: 8 #  